[package]
name = "hypher"
version = "0.1.0"
edition = "2021"

[features]
default = ["full"]
full = ["english"]
english = []

[workspace]
members = ["bench"]

[profile.dev.build-override]
opt-level = 1
